# Generated by Django 5.0.4 on 2024-04-23 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_is_denounced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_denounced',
        ),
    ]
